
import { Skill, SkillGroup } from './data_interfaces/skills'
import { SourceStatus } from './data_interfaces/metadata';

function QuickSkill(id: string, name: string, description: string, group: SkillGroup): Skill {
  return {
    id: id,
    name: name,
    description: description,
    group_id: group.id,
    source: "",
    source_type: SourceStatus.Unknown,
  };
}

const usable_ids: string[] = [
  "Ne2Uu7OCRY0BRD2y_6QR-",
  "6CUx_2m05Fc04typyuv8L",
  "Y0TqMTFEZZcafCu645MOk",
  "n-l04OtbJmGVxNebCo9pj",
  "3xHD_CsYffLkoT1Dx__jt",
  "ZL2jqbH6y7OjKGV5PFOJy",
  "J038FQMTB4LfzYm6wXlPQ",
  "BTT4OUG3erBo1hLMN7PKc",
  "PsJFmKC9qIX6BoPKBSbVB",
  "unVn077TqpEQ5OIanznHB",
  "Ya53_33groVdj0GcWPATT",
  "jvRaC3gxG0eUz3JfhVgGn",
  "eukn82D4FHIdOyHStnDgi",
  "hSAnQbTOiG1w0INTCATlR",
  "IChH3CCvBaSj-uZzjPQwt",
  "zN3uagFziK00_C1_udhAb",
  "bnqqEMiwWNUvYXvHbaBc7",
  "o3bm3ocSBmexk3OHXNydO",
  "G-xb8v7R8VgXokJGbbzYb",
  "ksG7yE1zQX17dL2pAzT8C",
  "FoZPXOjm7rkzBCxBo_Vjv",
  "An5qyW9O_oHUG4MvH6utW",
  "5fRRLeCi9rht-Rw1Sp7xT",
  "PwIftegnRVxnbCcUL0qTB",
  "5LqyZGFYaX2w_PH90jY7_",
  "xcrKlO2-Gy_gSU9-70-Cr",
  "Ueh9ZiaLr7fQpXlZEyxoS",
  "-AQ-ponvq052vTFEJuWbq",
  "piLeCGUM9BuibX_zBylBS",
  "okbx15lvgvzKotptu6bz2",
  "is3WJxSUaHuu5jj877ltY",
  "92vaX-8BflyxA62svUJX3",
  "0ZkGFltxTu-NrvoKaCo4F",
  "nLsJViST_PWYYKpY4RNbT",
  "ZiwuPf2T_B4hVT8TUpzGF",
  "uYxCWU6t3GvLShW_QytZG",
  "HJrsYKMClbwXEAFhPkyRp",
  "3t_OPH41YiYhZjl7DSiTe",
  "PAKA_GeWGlJlshaY1xasx",
  "XJdaAKA6ySwLHtVX2jqJG",
  "7Bv6UszxaQD5CKwlR41Dv",
  "acBDHgaTN2PbT9mjB2JRU",
  "sIP5OPzDtWiaCHBOiDIKH",
  "ysh6X0sBMOGy_Y5WRgcRh",
  "D_zjDp7CN24vV4weyT_do",
  "lw6ntiOq5IYlv6Va52aVo",
  "U7P9td_Zym9j9Hi2ydBpk",
  "XJu5xVktDSYXCVoDy4toR",
  "Wif9UdWKpinB0rQRa5B5U",
  "tnX8QH8mZWAUqS_fss7uN",
  "ipL_3fcrOKylqxIjLDTrj",
  "c47O9I_TNCV7msh-qV-ZZ",
  "VXwfIb_Rsh1IgppI0mtye",
  "Ayp0C3O3Ny9fMSdehsemE",
  "6oG_YDTT_1i4GOz1SKTeh",
  "C0pPgtzZpP98ngMqzFw9i",
  "swwBChltfl2A8XEloUwu9",
  "M-laXpoZIWTNAurDeeu2D",
  "eeJiOTYZe_p-j4j65z2qf",
  "DKE5E95q51-5bKc7RkJnp",
  "jXaIsTARITooga1NhWJGw",
  "cfUtTxxuyWPk0niYoPeHh",
  "fgPFucHE20N09Awg9805u",
  "wfHPLqzu-UNNz7FxBXtzU",
  "fH6-xVxRDbSQd1xCPbiO8",
  "lVePipNDtR7lQZdwA5aqK",
  "q5lNWrUdk5UpSBRyBV86A",
  "0IZ4BpdfvVRQcSlF3FSqa",
  "nsZGhti8nHIHl85S2TnoV",
  "9hCjCtUGeCOCYAPCiLNpt",
  "TNOIi9G8m2TriLZXJ6LY7",
  "sZBtqlh-viOhnfw06jaXh",
  "dv_evs8eyQ__EdmM_YsAv",
  "KBsDpFN_Y6E1bjv6E_3Zv",
  "2KBiGd_TiJPik1Km3_Xy2",
  "fYLTSqQlU3ktr552yA_BM",
  "6JwQNfLWxh3NQK9OyTrM3",
  "FbYGV72P5rhCcBggD6QQd",
  "I-x6HPu0au0hYVE9Jf__x",
  "Oxlp_cYzD3SjrFt4d0uSx",
  "P7Ramk0N64jSqsCqn7UcX",
  "NXutncVS-106d41IfQelA",
  "lH97EaoC6j5dJJYinkEHS",
  "V_pPltyykRKDglx84JTMF",
  "OPZPw9YiNSqU7fQLbXpFB",
  "WwHNcT7RtOLjhTvmoCTgA",
  "54yXWhJ8h0n7V-KbREhLl",
  "cWIZGpSGGOYPt0BT1_3a8",
  "SclsyxiCg8GdWslZ9xYx0",
  "gWAlEOyVc9tUoem7dKeVb",
  "jcCo9qgG1zxgVjKQUNp1z",
  "TekQq7EOP7slnADcSbMtG",
  "ka35Fmtwp87AJ7vrjmgnU",
  "IpFnwP043Emmvoan_VDbm",
  "HULNl92NyrEv8Bqf719de",
  "ete8QCyi_dB-1b3a7LgpQ",
  "5L5sVNFK0mSd_TzL2heZn",
  "CWPAU4GvbOTMvsxsmNV8I",
  "VlmDN56inu8wShJn4zX-5",
  "dcZ4t9BFbURici86bHXMu",
  "L0yUaLofyzqK1-pug19Hn",
  "kiDMcYMBg7HSCcHPAtsKD",
  "1I7An9LUMdfbLKVdchT0P",
  "WSByhIn-8KRgkBlbHkRdu",
  "_Q51nFrTbYOEyA771EVJZ",
  "J4O_W39ks0EFQVvtzixFI",
  "eR4AG3tmre2RtHVF9g8pg",
  "ARsKXEKFtuGt1a8lC0zt-",
  "JsTPR94FUbLHO9OyHhaer",
  "F5mMvDPcp_n99l_gKGiIh",
  "e6rzN3sW7t_f3djVHxBCs",
  "0bydmBQ3185jiWa7FX99k",
  "gE8FRG7FyFUQXqRQ26Qxg",
  "FSe-aixt5FDFcoDBpkNPg",
  "VW0Wenz0fHTtOekMq-DiA",
  "WbBAiQ_n8upypZ8Efj6b-",
  "NL6_XNRaRGfaYOP6AjS4y",
  "MdO0SVxwOqu9_wjtYSkNG",
  "X-q7P6JEITrM0-2ucNpeK",
  "g7Q4Ho6_lPmJkO61jy_Xh",
  "oAa08Twcdr2cNiJyOfDeA",
  "atvsZqsiJE4BtqjR-brFo",
  "DD3jMBm2wyDxgOAUaH6TL",
  "Vk7Wfn6l0wCGrYRbjKzvj",
  "C_ihJ0hdYtNupeJ-Q4hWo",
  "CtAglo0oZtzuatMB-tOeH",
  "ZnNUflNrF9j3y86ENMKpo",
  "2hY_cDXsZlBvEGG47nhEI",
  "0kClH_v3O6-HUrtDe3vNP",
  "lqeGyVuZj3DrKyLrCUuke",
  "K3cyTDZecbZjbhDxSRYZS",
  "XjPZ-XweqTpmHEhl_9-nX",
  "5LJGX4U2v0iNMXXGwaXWi",
  "GZXWN4B4pOsXJ-YEBLI0e",
  "juTZSg1eQw0w65eA0wIl4",
  "SMzlYB6_mTUTUf1FNQYXh",
  "ZA-NpPvhTvxF_2FI9igsJ",
  "93jnEsLNTUYzuDP1uPg8b",
  "BOhce-WPk-jkJ3n_yM4cT",
  "FKd8mmfC7jAn5Ajv-C2im",
  "sxZCLXa6_gN6ppbFvaeSq",
  "JXOotwR3LZLcIyLDVX9t9",
  "x4mEd5kTTBBLOzg-xhmIw",
  "cqOwykVTbUQvd3gmz-PpP",
  "7gSyLnqJNpXAp5UeuqXgk",
  "jaBXmM4UflDA_bmN2qeLK",
  "t4quXnLCtD8b7jDQRDPpi",
  "X--csQzT-_cDgsjDiXd0C",
  "8g-dpZKjwPdTwaPqV4Ouc",
  "Qp0_hnSJScWkCRcWLfwcB",
  "4ee60a82-4bd5-43ab-ad",
  "971a22f2-4c8a-4174-b0",
  "354ce22f-6723-476c-91",
  "d32196d7-9f15-4301-80",
  "b1374b95-3822-4903-a2",
  "0f1b6e44-d38d-46d1-b5",
  "155b7118-9c46-486a-bb",
  "cdd92697-2dfa-43cc-bf",
  "a26ebc01-6d41-4e46-ba",
  "3be8fdbb-5757-410e-89",
  "7cf9c69e-66b3-4b34-bf",
  "18926746-e85a-47d7-b4",
  "4d20625f-89ee-4a09-87",
  "8de7205c-c142-4bcd-8b",
  "4e74dfc7-1857-4696-89",
  "219c4272-5289-43db-b6",
  "d78ad66d-fbf2-4915-89",
  "e36d1ba7-f58b-47fd-96",
  "32671725-a9d3-4aa0-83",
  "89c7d2b0-5484-46fb-bb",
  "e5c3e9e3-4eb4-45a5-9c",
  "f34e7623-9838-4bbd-a2",
  "d0caf4e0-3b90-4e0b-af",
  "d43a90e8-e689-41b3-be",
  "b208857a-9f84-4bfd-9b",
  "5b550dfa-c012-4b08-b4",
  "ee37d571-0031-4007-82",
  "609ad3f6-e968-4600-a3",
  "f94c1c2a-cd99-4c0a-bd",
  "c0f27a93-c6b2-4f28-95",
  "57a3daed-c68e-4829-9f",
  "b7cd3ae3-b052-4021-82",
  "a44c95a3-0878-446f-ad",
  "280ee510-d6f3-4165-a3",
  "e2cc3143-a882-4861-84",
  "42f93bb4-0529-4091-82",
  "9b7ce656-ec60-4d83-be",
  "cd53135b-7c01-48ff-ae",
  "d47f27d2-8439-446e-b4",
  "ede0672b-55f4-415d-ae",
  "aed4a9df-6368-4ede-91",
  "61a223d1-5595-4f69-84",
  "24c94678-2175-4663-8e",
  "7565bc42-0887-4c52-a7",
  "fa7ded74-4b90-4848-98",
  "f3f26b55-35bf-4629-a9",
  "6f5dec1d-4d22-435f-8a",
  "af25efe8-2b4b-49f1-8c",
  "fef4fdde-6476-4404-a0",
  "4d106f29-2b71-4730-89",
  "1923acc0-eeee-4a5d-92",
  "c8fb8942-0182-4b51-93",
  "a36ba462-c788-4cbe-91",
  "9d529462-0192-4488-ac",
  "5184baf3-20b5-4169-93",
  "cea4396f-7e39-4c03-b0",
  "a2c5ac83-888e-4fc2-95",
  "f604deed-ec12-47dd-93",
  "9d46f549-ed7b-4954-bb",
  "d8c4c530-8a09-4475-94",
  "d6a1261f-a6d4-42c2-be",
  "4fb8201c-9b08-4bc1-84",
  "aaf13b6d-9b0e-4e53-bd",
  "e7217428-54a0-4439-ad",
  "98e61f81-351a-4a46-b5",
  "7ce066be-d0ba-4d3b-b4",
  "6471217e-fde9-4d95-92",
  "6fd34439-24e1-418b-b1",
  "faea5e9c-791f-432f-9b",
  "bbaa5721-6164-41f9-b1",
  "2cc26a68-09f9-4c05-ad",
  "0cb8f677-17df-4e97-9c",
  "9c72994f-30a1-40c5-af",
  "541749bc-6075-422f-9e",
  "eaedf848-f512-4e05-ac",
  "8cb374c9-0f2e-471b-b5",
  "3633b3b9-e374-4796-b8",
  "bc350194-fdaf-4e2b-ae",
  "9836a2db-cc29-4a04-b8",
  "e77671d4-b2b9-4dd3-b6",
  "8d2ea2fb-f2fc-4b04-b4",
  "e8bea9c9-31bd-4a5d-9c",
  "e697fb6d-ae9e-4cb7-ae",
  "4313f940-2938-45e8-ac",
  "39fbf33c-49b2-4d41-95",
  "aff66023-46f3-4512-b0",
  "1661db28-03fb-4174-94",
  "5ac1bf0a-e69a-41d2-8e",
  "90f57386-6e6f-4776-95",
  "e28af77d-7e63-497f-89",
  "5ae7c9d9-9d9f-4517-89",
  "54aa9904-49e6-404f-9c",
  "6d75cf24-2555-4131-a9",
  "19c16aca-9683-48ca-8b",
  "244a1660-f6f2-4ba5-92",
  "cf10001f-7b53-423b-b1",
  "889664fd-abdf-44a0-8a",
  "a56251b6-db9c-4c65-b4",
  "0666fa49-7483-4a4d-ac",
  "bc7d1771-978f-42e9-8b",
  "da5713ce-6684-4066-bb",
  "bf5e8614-f9cb-47c7-a1",
  "88c80045-e836-4330-9a",
  "2b2e4b8e-2bb1-4cc2-83",
  "a5798034-5688-4441-80",
  "f2482c9b-7cc2-49be-9d",
  "49e30765-103f-4ba8-b7",
  "d2d6122c-b1a3-4f0b-a5",
  "3bb6fd83-3c4d-46f6-ba",
  "c4bdb470-1959-461d-83",
  "13e406bf-c8a5-42ac-85",
  "75f56807-943d-4ec5-91",
  "69e99da4-ea47-4ebf-a7",
  "1d6b7fff-07f9-493a-86",
  "dd8ded67-db09-40fc-a9",
  "8d630c3b-1cc9-4c48-9a",
  "17e27566-a6c0-4dd7-ac",
  "e3df5956-fca7-4fb2-9a",
  "e6e148e0-84c0-410b-8d",
  "5d607254-5d60-4a4f-b9",
  "f24b780d-9616-433b-b0",
  "f7f5f61d-2ab5-4207-b8",
  "cd237335-b7da-4713-80",
  "fddc0dc0-7e7a-4436-ad",
  "0e382fda-51cc-4cf2-af",
  "3f3357d0-7b44-40ba-b6",
  "b0fc4f8f-285b-47b8-ae",
  "16d22b1d-7d83-4ab3-ab",
  "dfdaa502-6a93-4840-9c",
  "571b3dd7-6c53-4e2f-a2",
  "3356134e-eff1-449e-9a",
  "ab4ddfe7-f6a7-4c27-aa",
  "143c7d5b-5517-45dd-91",
  "9c2c8020-4323-4e51-b1",
  "3700f412-32a1-476b-bd",
  "1702bd80-1b66-4376-a9",
  "a432ad2c-33ae-4739-b3",
  "937819b1-e481-4716-ae",
  "d06aa4c6-3be2-484c-b6",
  "187d6193-d803-4e1f-9e",
  "781aeb6f-d662-4adc-89",
  "62cad9ce-76b3-4f86-95",
  "d748bdd6-18bb-44ae-ad",
  "b83ca175-cd16-41d6-8e",
  "33e530b3-af9f-4fc5-a8",
  "64b9bcf9-4c97-42d3-aa",
  "e9008718-3616-4839-a5",
  "b5aa1540-20eb-480f-8a",
  "60477436-b9f2-44d9-aa",
  "89ab988d-afc1-42ef-a7",
  "f5c18981-5034-48d9-ab",
  "6a11b575-649b-457d-a3",
  "e1242b78-ab3e-44ef-94",
  "3631ac2f-8bd1-46c4-8d",
  "fd8eb75a-1139-41cc-9a",
  "e3734d73-f52d-4096-af",
  "5862df07-5bef-49e0-97",
  "f39e17cf-25af-4140-8f",
  "32ebbc44-3d06-47e5-a9",
  "e34a08a4-d08b-45c1-87",
  "0c795a49-c39c-4be0-99",
  "c091a422-10d5-4084-94",
  "eaca1a1a-a185-4cb9-ac",
  "763952c9-8640-42d6-8f",
  "e51083d1-f97c-4793-95",
  "f5611011-f159-44e1-87",
  "60e3c079-d212-485d-b4",
  "dbedb38e-5300-4121-81",
  "666b7e09-819b-4e60-ba",
  "c8556e00-9d18-44c7-b5",
  "792fbde6-d626-42d7-b0",
  "adbd2356-01cc-4b98-ad",
  "3d03f77c-bca3-421a-83",
  "ce699f8a-b8e9-4ad1-8a",
  "1982b53b-f3f6-4453-98",
  "a5ac9c7a-de64-4e14-8a",
  "01f8ba83-8a9c-4864-97",
  "ce441a04-6059-451b-80",
  "0ff3c4f6-3fe0-409d-94",
  "2290ad27-39f0-4dbd-8e",
  "73695154-5c39-4bd7-84",
  "b89fc8f6-cb82-458b-a6",
  "4865cbe4-472b-4b12-8d",
  "87c86a76-1d77-4fce-85",
  "c4856366-b4b9-47f7-bb",
  "201aff08-f152-47a9-9f",
  "4b6a68a6-09de-403d-a2",
  "d2b660c1-2d6c-4dbe-80",
  "74b5e448-a633-46b1-9f",
  "85876272-648a-43aa-a0",
  "e4aa6bf0-dc8e-49f1-a4",
  "ca20383b-b619-4107-a3",
  "061454ac-150c-4921-92",
  "1948720b-e139-4cb1-8e",
  "b39155e6-db8c-445e-80",
  "1a6385a9-1021-4abb-a8",
  "d12cf1e3-26ae-4173-a0",
  "11f890ae-1f40-40d1-a6",
  "67acdfc2-80c1-42f2-a0",
  "8d378dae-eef4-4949-95",
  "de68e24f-9ad3-483d-a7",
  "96cb55eb-9a15-47f2-a0",
  "2702acd0-c38a-469b-b3",
  "b1da031b-27f9-4def-b3",
  "afa97acf-d547-47ae-a8",
  "55e24c89-f698-406e-9e",
  "6199c8a0-0ba9-4c9b-b7",
  "8f21e650-db27-4650-86",
  "d664bf27-27c4-431a-99",
  "75ab9c7c-990f-48c1-ae",
  "39920d8b-bb36-40d3-af",
  "1c1f2e54-c643-4b96-b8",
  "ae54f27f-11d9-42c6-b5",
  "14839ef9-7aaa-44d1-82",
  "0eaa8ec3-ef41-4d4d-94",
  "8c7d802c-ea11-4cbb-a2",
  "87d4ed68-6b80-4c77-8f",
  "16d74cfc-f992-4cf2-b9",
  "f37ead8c-7761-4ba2-b1",
  "35d72c16-8d83-4827-bd",
  "50667675-a7e3-49e0-84",
  "04437bd7-5f8a-4d85-84",
  "451d2803-4c2f-474c-b2",
  "a6a013a5-0d11-4464-ad",
  "5f2dd871-7c77-493c-ab",
  "d7c8009c-1a18-477c-a3",
  "a428f054-5ead-4ec7-bf",
  "37fb21e1-e266-40a1-92",
  "b88ab756-63b6-4375-b3",
  "aeea2432-174b-4647-ab",
  "9c54f651-ed60-43f8-93",
  "a57c958a-5e65-4d6e-b3",
  "2ad6725a-a674-4bdb-93",
  "c69f78c8-61c8-430a-9d",
  "90796171-9098-4e52-af",
  "3f38e50d-18ca-490b-8a",
  "1d075d4d-b788-4c73-a4",
  "d5f16a73-72f5-4a7c-9e",
  "a72bc48c-7aef-4a1f-a6",
  "9a75df9e-a74b-4613-b1",
  "5052754e-0ac2-4994-8f",
  "76f00565-4407-43da-b3",
  "c8bcd7de-ebaa-4768-83",
  "6f543972-8f33-45e3-a7",
  "328b197e-7e68-48af-b7",
  "befff339-4696-4be7-9e",
  "0240f2c0-3cb5-4b13-a1",
  "a9fbf62e-cbe8-4985-9a",
  "e1b273c8-9b7d-4a9e-9f",
  "ef431c38-762a-4399-89",
  "b3a7b3f6-fca2-46c5-8a",
  "f21babc2-3385-4061-b9",
  "65ccbc76-c886-4492-a3",
  "5b90f575-ebd4-46eb-ab",
  "f65a7a22-0319-4f7b-94",
  "e038136b-47c3-4121-a5",
  "61d0601f-5169-40ef-a8",
  "957f3027-912f-46ea-b3",
  "72d460aa-eb9e-45a2-81",
  "6cb207af-3687-4ad4-a2",
  "96386a17-3e99-46a3-a6",
  "822e9fe4-e97a-4847-8f",
  "67354e92-d400-4230-9f",
  "5fe21e3c-42db-4a8c-b4",
  "07b80eb5-8ac6-451e-9a",
  "48a2dd6c-b28d-4956-96",
  "d464983a-dc30-4ed5-9f",
  "7293bea6-3592-49ed-93",
  "e804b460-6e54-4fe5-b6",
  "19dabd4a-7fdb-4c1c-b4",
  "1b095eda-22e8-4133-8e",
  "53fae42c-35c5-45f0-95",
  "b10999f8-213c-42ed-94",
  "3f2e5b64-bb44-471b-8d",
  "7edc4985-7fc8-45fd-b6",
  "e0f862c8-de9d-47e2-a6",
  "bb83c19c-9e79-43e4-83",
  "c5f5c046-6c2b-4211-aa",
  "7a9bb28e-0cde-412a-a0",
  "1745c784-c83b-4b29-95",
  "9450e12f-cbd1-4e63-aa",
  "2c8dff78-6088-43b4-a9",
  "25b896ea-270c-43c4-a9",
  "a25dab9c-3640-4b8b-aa",
  "869b6f2a-8fb0-4bbb-9b",
  "5a5b6b98-9260-4524-ab",
  "f1f4df91-f400-4bc9-8b",
  "168cda6f-3487-4fad-8f",
  "81725ffe-6166-41ba-aa",
  "16a70eed-5552-45db-a3",
  "1765a342-5174-488c-a3",
  "5243a72b-b6ab-4dc7-b8",
  "fd6b93e9-139d-4e82-bf",
  "99fb1e48-b95c-486a-9a",
  "ece87b36-5cd8-4549-b9",
  "2e8f98fa-6b87-461c-a6",
  "a546bdd2-bd3b-48a3-8c",
  "9318b531-c79a-4fc5-94",
  "f782d7a3-bb42-4a53-9f",
  "3c49d475-56dd-418a-98",
]

export const initialSkillGroups: Record<string, SkillGroup> = {
  All: {
    id: usable_ids.pop()!,
    name: "All",
    availability: [{ id: usable_ids.pop()!, rarity: 0, restrictions: [] }],
  },
  Academic: {
    id: usable_ids.pop()!,
    name: "Academic",
    availability: [{ id: usable_ids.pop()!, rarity: 0, restrictions: [] }],
  },
  Combat: {
    id: usable_ids.pop()!,
    name: "Combat",
    availability: [{ id: usable_ids.pop()!, rarity: 0, restrictions: [] }],
  },
  Shooting: {
    id: usable_ids.pop()!,
    name: "Shooting",
    availability: [{ id: usable_ids.pop()!, rarity: 0, restrictions: [] }],
  },
  Speed: {
    id: usable_ids.pop()!,
    name: "Speed",
    availability: [{ id: usable_ids.pop()!, rarity: 0, restrictions: [] }],
  },
  Strength: {
    id: usable_ids.pop()!,
    name: "Strength",
    availability: [{ id: usable_ids.pop()!, rarity: 0, restrictions: [] }],
  },
};

export const initialSkillState: Skill[] = [
  // All
  QuickSkill(usable_ids.pop()!, "Ambidextrous", "The warrior can use their offhand weapon(s), limbs or tails without the -1 to hit modifier, they can also now critically hit with these attacks also", initialSkillGroups["All"]),

  // Academic Skills
  QuickSkill(usable_ids.pop()!, "Scrounger", "When creating or buying any limited use items (e.g. ammunition, bombs, poisons etc) the warrior can pay 50% extra (rounded up) to gain another copy (so two lots in total).", initialSkillGroups["Academic"]),
  QuickSkill(usable_ids.pop()!, "Battle Tongue", "This skill may only be chosen by a leader. The warrior has drilled his warband to follow short barked commands. This increases the range of his Leader ability by 6\". Note that Undead leaders may not use this skill. (RB 123)", initialSkillGroups["Academic"]),
  QuickSkill(usable_ids.pop()!, "Sorcery", "This skill may only be taken by Heroes capable of casting spells. A warrior with this skill gains +1 to his rolls to see whether he can cast spells successfully or not. Note that Sisters of Sigmar and Warrior-Priests may not use this skill. (RB 123)", initialSkillGroups["Academic"]),
  QuickSkill(usable_ids.pop()!, "Haggle", "The warrior knows all the tricks of bargaining and haggling. He may deduct 2D6 gold crowns from the price of any single item (to a minimum cost of 1gc) once per post battle sequence. (RB 123)", initialSkillGroups["Academic"]),
  QuickSkill(usable_ids.pop()!, "Arcane Lore", "Witch Hunters, Sisters of Sigmar and Warrior-Priests may not have this skill. Any warrior with this skill may learn Lesser Magic if he owns a Tome of Magic. (RB 123)", initialSkillGroups["Academic"]),
  QuickSkill(usable_ids.pop()!, "Wyrdstone Hunter", "The warrior has an uncanny ability to find hidden shards of wyrdstone. If a Hero with this skill is searching the ruins in the exploration phase you may re-roll one dice when rolling on the Exploration chart. The second result stands. (RB 123)", initialSkillGroups["Academic"]),
  QuickSkill(usable_ids.pop()!, "Warrior Wizard", "This skill may only be taken by spellcasters. The mental powers of the wizard allow him to wear armour and cast spells. (RB 123)", initialSkillGroups["Academic"]),
  QuickSkill(usable_ids.pop()!, "Scribe", "The warrior is a natural adept at writing and making scrolls. Any warrior with the ability to cast spells or use prayers may take this skill. It allows them to make a scroll before the battle and inscribe a single spell or prayer upon it that they are versed in. The scroll may be used just before they are about to cast the spell or prayer and allows the caster +2 to his difficulty roll. Once used the scroll will crumble to dust and is useless. Scrolls may not be saved up from battle to battle if they are not used. (TC7)", initialSkillGroups["Academic"]),
  QuickSkill(usable_ids.pop()!, "Mind Focus", "The warrior possesses a great strength of mind which allows him to concentrate beyond the levels of most normal men. This skill may only be taken by a warrior capable of using prayers or casting spells. When using a spell or prayer the warrior with this skill may reroll one dice roll used in the difficulty roll. (TC7)", initialSkillGroups["Academic"]),
  QuickSkill(usable_ids.pop()!, "Tactician", "This skill may only be taken by a warband leader. The warrior has a great tactical mind and can often find the best positions for his warriors to meet the oncoming attack. In any scenario the warband leader may reposition his warriors after his opponent has set up and may even advance them up to 12 inch onto the board instead of 8 inch. (TC7)", initialSkillGroups["Academic"]),
  QuickSkill(usable_ids.pop()!, "Hunch", "This skill may only be taken by the warband leader. The warrior has an uncanny knack of placing their men in the right place at the right time, as if they sense danger through instinct alone. In any scenario the warband leader may position up to 3 of their warriors capable of earning experience in a single ruined building (that does not contain an objective) on the board that is at least 12 inch away from an enemy model and not in an enemy deployment zone.", initialSkillGroups["Academic"]),
  QuickSkill(usable_ids.pop()!, "Magical Aptitude", "This skill may only be taken by a warrior capable of casting spells. It may not be used by Sisters of Sigmar or Warrior Priests. The warrior has a keen aptitude for magic and can push himself beyond normal limits to produce a storm of spells. The warrior may attempt to cast two spells each turn as long as he is not in hand-to-hand combat. After attempting the first spell, he must take a toughness test. If he passes he may attempt a second spell that turn, or even cast the same spell twice. If he fails he must roll on the injury table immediately with no saves treating out of action results as stunned instead. (TC7)", initialSkillGroups["Academic"]),
  QuickSkill(usable_ids.pop()!, "Driver", "A wagon driven by a Hero with this skill may re-roll results on the Out of Control Chart. The second result must be accepted even if it is worse. (BTB)", initialSkillGroups["Academic"]),
  QuickSkill(usable_ids.pop()!, "Scholar", "Only warriors capable of casting spells or using prayers may pick this skill. Whenever the warrior may learn a new spell or prayer through an advance, he may choose which one he learns instead of determining at random, or he may decrease the difficulty of any one spell or prayer he already knows by -1 permanently. (BTB)", initialSkillGroups["Academic"]),
  QuickSkill(usable_ids.pop()!, "Trap Expert", "The Hero will never advertently set off traps but may be subject to their effects if standing too close to one as it goes off! An attempt can be made to disarm any traps the Hero comes across. The warrior stops at the trap during the Movement phase, and may do nothing else that turn. To disarm any simple traps, the warrior must roll 6+ on 2D6. To disarm any special kinds of traps or a complex trap, the warrior must roll 8+ on 2D6. If unsuccessful, an Initiative test is required. A failed test means the trap has been inadvertently set off! A Hero with this skill can repair and activate dud traps or restore previously de-activated traps, in which case they become active traps. To determine what an activated trap becomes, roll a D6: D6 Result 1-4 Simple: The trap is a simple device. 5-6 Complex: The trap is a complex design. A previously disarmed simple trap or complex trap will always revert back to what it was originally. If restoring simple traps, a roll of 6+ on 2D6 is required. A roll of 8+ on 2D6 is required to restore a complex trap. Failure will mean that the trap has failed to activate. (TC 17)", initialSkillGroups["Academic"]),
  QuickSkill(usable_ids.pop()!, "Pawnbroker", "The Hero is skilled in finding the best price for sold items and as such gains an extra 2D6 gold per item that the warband sells (up to its full value) if he was not taken out of action.  (MiM)", initialSkillGroups["Academic"]),
  QuickSkill(usable_ids.pop()!, "Streetwise", "A warrior with this skill has good contacts and knows where to purchase rare items. He may add +2 to the roll that determines his chances of finding such items (see the Trading section). (RB 123)", initialSkillGroups["Academic"]),

  // Combat Skills
  QuickSkill(usable_ids.pop()!, "Axe Master", "The warrior may parry with axes as per normal parrying rules. Any axe", initialSkillGroups["Combat"]),
  QuickSkill(usable_ids.pop()!, "Defensive Flurry", "The Parry rule is changed for this warrior as follows: after taking normal parries the warrior may opt to make additional parrys, using his normal attacks to do so. The warrior may continue to attempt to parry as many incoming blows as he has attacks. If the warrior still has attacks left at the very end of the HtH phase then he may try to hit with his remaining attacks. The warrior can attempt to parry a specific incoming blow only once, but may attempt to parry multiple attacks from the same opponent. This skill can be combined with other parry affecting skills and weapons. Must be able to parry with a weapon/buckler.", initialSkillGroups["Combat"]),
  QuickSkill(usable_ids.pop()!, "Disarm", "The warrior may use 2 attacks attempt to disarm a single opponent. To disarm the opponent, the warrior must declare what weapon he is disarming and then roll to hit the foe at a -2 WS for a single handed weapon and a -3 WS for a 2 handed weapon. If succesful the opponent must fight without the designated weapon until he recovers it. The foe recovers his weapon in the first Recovery Phase out of HtH. Not vs natural weaponry. REQUIRES 2 ATTACKS ON CHAR PROFILE", initialSkillGroups["Combat"]),
  QuickSkill(usable_ids.pop()!, "Spear Warrior", "If the warrior wields a Spear he gains an additional First Strike Attack with that spear on the first turn of combat, regardless if he charged or got charged himself. Spears or pikes", initialSkillGroups["Combat"]),
  QuickSkill(usable_ids.pop()!, "Finishing Move", "The warrior may use two attacks (from their profile) to make a single attack at +2 Strength (does not gain additional weapon bonuses). The blow is resolved last AFTER 2 handed weapons. Any left over attacks the warrior has (e.g. if they have 3 attacks on their profile, or an off-hand weapon) work as normal. No restriction on weapon type. As normal a single model can't knock down and then finish off another model in a single combat phase, no matter when attacks are made.", initialSkillGroups["Combat"]),
  QuickSkill(usable_ids.pop()!, "Roll Away", "The warrior is adept at giving himself time to recover. If the warrior is knocked down he may make an Initiative roll, if he passes it he may immediately move 2\" away from his opponent in any direction not blocked by intervening terrain or other models. This may save the Hero from taking further attacks from other opponents. The Hero cannot move into contact with another enemy in this fashion. This does not work with saves from helmets or the no-pain rule.", initialSkillGroups["Combat"]),
  QuickSkill(usable_ids.pop()!, "Dirty Shot", "The warrior may choose to make killing shot on any of his attacks. He is -2 to hit in addition to any other modifiers, but the target does not get an armor save vs the attack.", initialSkillGroups["Combat"]),
  QuickSkill(usable_ids.pop()!, "Sweeping Blow", "The warrior may use 2 attacks make a single sweep attack against all the models in base to base contact with him instead of making his normal attacks . Rather than rolling to hit, the model rolls a Str check to see if they manage to swing their weapon, if passed every enemy in HtH combat is hit, cannot be parried. No Strength bonuses granted by the weapons themselves are included but other weapon stats may be added if applicable. Any 2h weapons allowed.  REQUIRES 2 ATTACKS ON CHAR PROFILE", initialSkillGroups["Combat"]),
  QuickSkill(usable_ids.pop()!, "Steadfast Defender", "Allows the user to 'intercept' the first unit charging them in a turn. That unit needs to make a Initiative test and if they fail they stop 2\" short of you. Halberds only", initialSkillGroups["Combat"]),
  QuickSkill(usable_ids.pop()!, "Strike to Injure", "The warrior can land his blows with uncanny accuracy. Add +1 to all injury rolls caused by the model in hand-to-hand combat. (RB 122)", initialSkillGroups["Combat"]),
  QuickSkill(usable_ids.pop()!, "Combat Master", "The warrior is able to take on several opponents at once. If he fights against more than one enemy at a time, he gains an extra Attack in each hand-to-hand combat phase as long as he is fighting two or more enemy models. In addition, the warrior is immune to ‘All Alone' tests. (RB 122)", initialSkillGroups["Combat"]),
  QuickSkill(usable_ids.pop()!, "Weapons Training", "A warrior with this skill is adept at using many different weapons. He may use any hand-to-hand combat weapon he comes across, not just those in his equipment options. (RB 122)", initialSkillGroups["Combat"]),
  QuickSkill(usable_ids.pop()!, "Web of Steel", "Web of Steel: Few can match the ability of this warrior. He fights with great skill, weaving a web of steel around him. The model has +1 to his To Crit roll (5+ normally) when fighting in close combat. This cannot stack with other abilities that increase chance to crit.", initialSkillGroups["Combat"]),
  QuickSkill(usable_ids.pop()!, "Expert Swordsman", "This warrior has been expertly taught in the art of swordsmanship. He may re-roll all missed attacks if he is using a sword in the hand-to-hand phase of the turn that he charges and may re-roll parry attempts the turn he his charged. Note that this only applies when they are armed with sword like weapons.", initialSkillGroups["Combat"]),
  QuickSkill(usable_ids.pop()!, "Step Aside", "The warrior has a natural ability to avoid injury in combat. Each time he suffers a wound in close combat he may make an additional saving throw of 5+. This save is never modified and is taken after all other armour saves. (RB 122)", initialSkillGroups["Combat"]),
  QuickSkill(usable_ids.pop()!, "Shield Wall", "Models within 1\" of this unit, including this one, gain an extra +1 AS against ranged attacks as long as the warrior is not in Close Combat. Requires a shield.", initialSkillGroups["Combat"]),
  QuickSkill(usable_ids.pop()!, "Bulwark", "A defensive style requiring a shield in one hand and a hand weapon such as a sword in the other. A warrior armed with a single-handed weapon (sword, spear, hammer, etc.) and any shield, will only start to have their armour saving throw reduced from Strength 5 in close combat (other special weapon modifiers still apply).", initialSkillGroups["Combat"]),
  QuickSkill(usable_ids.pop()!, "Lunge", "Using a spear or dagger your warrior can strike foes that would normally be out of reach. Increase the reach of your melee attacks when charging by moving 1\" further forward. Lunge attacks can only be avoided with the Step Aside skill on a roll of 6. Armour saves apply as normal. (MiM)", initialSkillGroups["Combat"]),
  QuickSkill(usable_ids.pop()!, "Whip Master", "The hero is so skilled with a whip that he may re-roll all missed to-hit rolls when using a whip [or steel whip, or beastlash, or scourge]. Only one re-roll is allowed per attempt, and you must accept the second roll even if it is worse. (TC 14)", initialSkillGroups["Combat"]),
  QuickSkill(usable_ids.pop()!, "Man At Arms", "The warriors skill with a halberd allows them to switch seamlessly between thrusting and slashing. When using a halberd the model gains +1 to their 'To crit' roll and you may choose to roll on either the thrusting or bladed critical charts after you've rolled the critical hit die.", initialSkillGroups["Combat"]),
  QuickSkill(usable_ids.pop()!, "Frightful Crack", "The Warriors whip strikes cause a deafening boom. When using the Whipcrack Special Rule, a successful hit leaves the opponent at -1WS for the remainder of this combat round, even if the Hit fails to Wound. (MiM)", initialSkillGroups["Combat"]),
  QuickSkill(usable_ids.pop()!, "Weak Spot", "Aiming for gaps in their opponents armour the warrior strikes at the perfect moment. When dual wielding any sort of daggers, if both your main weapon and your off hand weapon hit, you will cause a wound at least a 5+ regardless of strength (if your wound roll would be lower use that), any wounds will then crit on a 5+ as well.", initialSkillGroups["Combat"]),

  // Ranged Skills
  QuickSkill(usable_ids.pop()!, "Heavy Pull", "The warrior has trained to use a bow with a heavier draw. All attacks made by the warrior with a bow are at +1 Strength and +1D6 range. A warrior with quickshot can only shoot 1 shot if they use Heavy Pull. Bows only.", initialSkillGroups["Shooting"]),
  QuickSkill(usable_ids.pop()!, "Quick thinker", "When rolling on the blackpowder misfire chart the warrior adds +1 to their roll, only a natural 6 counts as KA-BOOM!", initialSkillGroups["Shooting"]),
  QuickSkill(usable_ids.pop()!, "Firing team", "If in base contact with a friendly model the hero may reload their weapon for them in the shooting phase after it has been fired that phase. If doing so the hero may not fire their own weapon.", initialSkillGroups["Shooting"]),
  QuickSkill(usable_ids.pop()!, "Take aim", "The warrior can aim one of their ranged weapons in their shooting phase rather than shooting it. Next turn if they don't move they gain +2 to hit and +1 to wound on their first shot with that weapon. Note: To aim with a ranged weapon they must have been able to fire it that turn (so BP weapons that aren't reloaded can't be used). Only affects the first shot for Quick Shot, Prepared Shot, and repeater weapons. You can't prepare both this and \"Prepared Shot\" in the same turn. Can't be used with template weapons.", initialSkillGroups["Shooting"]),
  QuickSkill(usable_ids.pop()!, "Placed Shot", "The warrior may choose to make a placed shot instead of his normal shots(s). He is -2 to hit in addition to any other modifiers, but the target does not get an armor save vs the attack. Any non template ranged weapon", initialSkillGroups["Shooting"]),
  QuickSkill(usable_ids.pop()!, "Prepared Shot", "A ranger with this skill may prepare to fire quickly when already loaded. If a model did not run this turn unless Nimble and is not in melee combat they can prepare to shoot twice the following turn. Place a counter down to reflect this extra shot, if they move they lose this shot. Regular Crossbows only, if they move they forfeit tehir prepared shot.", initialSkillGroups["Shooting"]),
  QuickSkill(usable_ids.pop()!, "Quick Shot", "The warrior may shoot twice per turn with a bow.", initialSkillGroups["Shooting"]),
  QuickSkill(usable_ids.pop()!, "Pistolier", "The warrior is an expert at using all kinds of pistols. If he is equipped with a brace of pistols of any type (including crossbow pistols), he may fire twice in the Shooting phase (though note that normal reloading rules apply). If he has a single pistol then he may fire it in the same turn it was reloaded. (RB 122 - Official Errata 2002)", initialSkillGroups["Shooting"]),
  QuickSkill(usable_ids.pop()!, "Eagle Eyes", "The warrior's sight is exceptionally keen. He adds +6\" to the range of any missile weapon he is using. (RB 122)", initialSkillGroups["Shooting"]),
  QuickSkill(usable_ids.pop()!, "Weapons Expert", "The warrior has been trained to use some of the more unusual weapons of the known world. He may use any missile weapon he comes across, not just the weapons available from his warband's list. (RB 122)", initialSkillGroups["Shooting"]),
  QuickSkill(usable_ids.pop()!, "Trick Shooter", "The warrior can shoot through the tiniest gap without it affecting his aim. He ignores all modifiers for cover when using missile weapons. (RB 122)", initialSkillGroups["Shooting"]),
  QuickSkill(usable_ids.pop()!, "Hunter", "The warrior is an expert at getting his weapon loaded and ready. He may fire each turn with any handgun-based weapon (including repeaters). Weapons with multiple shots only reload a single shot but can be fully reload while moving.", initialSkillGroups["Shooting"]),
  QuickSkill(usable_ids.pop()!, "Knife-Fighter", "The warrior is an unrivalled expert at using throwing knives and throwing stars. He can throw a maximum of three of these missiles in his shooting phase and may divide his shots between any targets within range as he wishes. Note that this skill cannot be combined with the Quick Shot skill. (RB 122)", initialSkillGroups["Shooting"]),
  QuickSkill(usable_ids.pop()!, "Nimble", "The warrior ignores \"Move or Fire\" rules on any weapon that can be held in one hand (e.g. handguns, crossbows, etc). For weapons that require two hands (mortars, swivel guns etc) they may move at half speed and fire. Note that this skill cannot be combined with the Quick Shot skill. ", initialSkillGroups["Shooting"]),
  QuickSkill(usable_ids.pop()!, "Target Practice", "The warrior can fire a single missile attack when being charged. Models that stand and shoot suffer a -1 modifier to hit and hit at a range to where the charging model would start their movement. Normal reloading rules. If the charging model is injured they are placed halfway along their charge route.", initialSkillGroups["Shooting"]),

  // Speed Skills
  QuickSkill(usable_ids.pop()!, "Muscle Burst", "The warrior can strike with a dizzying number of blows in combat. If they wound an opponent they can pass an initiative test to immediately make an attack at -1S and +1SV. Also cannot be parried. Not usable with any weapon that requires 2 Hands to use.", initialSkillGroups["Speed"]),
  QuickSkill(usable_ids.pop()!, "Cross Cut", "The warrior may use their attack as well as their offhand weapon attack to go for a cross cutting blow to the head. Due to the precise nature the model is at -1 to hit with no rerolls allowed and no weapon modifiers included. If the attack wounds it causes D3 wounds instead and has an additional -1 to the enemies Sv. REQUIRES DUAL WIELDING", initialSkillGroups["Speed"]),
  QuickSkill(usable_ids.pop()!, "Fleet Footed", "The warrior gains +1 to his base Movement if max character profile allows", initialSkillGroups["Speed"]),
  QuickSkill(usable_ids.pop()!, "Leap", "The warrior may leap D6\" in the movement phase in addition to his normal movement. He may move and leap, run and leap, or charge and leap, but he can only leap once per turn. A leaping warrior may jump over opposing man-sized models, including enemies, and obstacles 1\" high, without penalty. The leap may also be used to leap over gaps, but in this case you must commit the warrior to making the leap before rolling the dice to see how far he jumps. If he fails to make it all the way across, he falls through the gap (see page 28). (RB 123)", initialSkillGroups["Speed"]),
  QuickSkill(usable_ids.pop()!, "Sprint", "The warrior may triple his Movement rate when he runs or charges, rather than doubling it as normal. (RB 123)", initialSkillGroups["Speed"]),
  QuickSkill(usable_ids.pop()!, "Acrobat", "The warrior is incredibly supple and agile. He may fall or jump from a height of up to 12\" without taking any damage if he passes a single Initiative test, and can re-roll failed Diving Charge rolls. He can still only make a diving charge from a height of up to 6\". (RB 123)", initialSkillGroups["Speed"]),
  QuickSkill(usable_ids.pop()!, "Lightning Reflexes", "If the warrior is charged he will ‘strike first' against those that charged that turn. As the charger(s) will also normally ‘strike first' (for charging), the order of attack between the charger(s) and the warrior with this skill will be determined by comparing Initiative values. (RB 123)", initialSkillGroups["Speed"]),
  QuickSkill(usable_ids.pop()!, "Jump Up", "The warrior can regain his footing in an instant, springing to his feet immediately if he is knocked down. The warrior may ignore knocked down results when rolling for injuries, unless he is knocked down because of a successful save from wearing a helmet or because he has the No Pain special rule. (RB 123)", initialSkillGroups["Speed"]),
  QuickSkill(usable_ids.pop()!, "Dodge", "A warrior with this skill is nimble and as fast as quicksilver. He can avoid any hits from a missile weapon on a D6 roll of 5+. Note that this roll is taken against missiles as soon as a hit is scored to see whether the warrior dodges it or not, before rolling to wound, and before any effects from other skills or equipment (such as lucky charms). (RB 123)", initialSkillGroups["Speed"]),
  QuickSkill(usable_ids.pop()!, "Scale Sheer Surfaces", "A warrior with this skill can scale even the highest wall or fence with ease. He can climb up or down a height equal to twice his normal Movement, and does not need to make Initiative tests when doing so. (RB 123)", initialSkillGroups["Speed"]),
  QuickSkill(usable_ids.pop()!, "Tunnel Rat", "Some warriors are at home beneath the city. They pick their way along the ledges as surefooted as a cat. Any characteristic-based tests being taken for scenarios set in sewers or elsewhere underground by the Hero can be re-rolled. (MiM)", initialSkillGroups["Speed"]),

  // Strength Skills
  QuickSkill(usable_ids.pop()!, "Strong Legs", "The Hero may use Heavy Armor and a Shield without suffering Movement penalties. When taking fall damage the strength of the blow received is one less (e.g. if falling from a 2\" high wall they would take 1D3 Str 1 hits).", initialSkillGroups["Strength"]),
  QuickSkill(usable_ids.pop()!, "Armour Master", "The Hero may use any type of armour.", initialSkillGroups["Strength"]),
  QuickSkill(usable_ids.pop()!, "Bell Ringer", "Unit can make a singular pommel/hilt attack. +1 to hit, +1 S, no Weapon Bonuses, foe Stunned on a 2-5 on Injury Chart. Can only be used with a 1 handed weapon", initialSkillGroups["Strength"]),
  QuickSkill(usable_ids.pop()!, "Shield-bash", "The first time in each round of combat where you make an armour save (and aren't knocked down or stunned) you automatically hit them back at -1 S (with no weapon bonuses). Must have a shield/buckler.", initialSkillGroups["Strength"]),
  QuickSkill(usable_ids.pop()!, "Beast Hunter", "The unit is an expert at killing anything beastial. When fighting any animal, creature or beast (usually creatures that can't gain experience, decide before the game if questionable), the warrior can reroll all rolls to hit and wound. Additionally, if the beast is put OOA by their hand and dies from injuries they can take a trophy from the beast that can be sold for 25gc.", initialSkillGroups["Strength"]),
  QuickSkill(usable_ids.pop()!, "Pit Fighter", "The warrior has learned how to fight in enclosed spaces from his time in the dangerous fighting pits of the Empire. He is an expert at fighting in confined areas and adds +1 to his WS and +1 to his Attacks if he is fighting inside buildings or ruins. It's a good idea to define which bits of your terrain collection count as ‘buildings or ruins' at the start of a battle to avoid confusion later. (RB 123)", initialSkillGroups["Strength"]),
  QuickSkill(usable_ids.pop()!, "Resilient", "The warrior is covered in battle scars. Deduct -1 Strength from all hits against him in close combat. This does not affect armour save modifiers. (RB 123)", initialSkillGroups["Strength"]),
  QuickSkill(usable_ids.pop()!, "Fearsome", "Such is the reputation and physique of the model that he causes fear in opposing models. (RB 123)", initialSkillGroups["Strength"]),
  QuickSkill(usable_ids.pop()!, "Strongman", "The warrior is capable of great feats of strength. He may use a double-handed weapon without the usual penalty of always striking last. Work out order of battle as you would with other weapons. (RB 123)", initialSkillGroups["Strength"]),
  QuickSkill(usable_ids.pop()!, "Unstoppable Charge", "Warrior gains +1 WS when charging. Additionally when intercepted during a charge the warrior continues until they reach their target. An intercepting model follows them and end in combat with them as well. ", initialSkillGroups["Strength"]),
  QuickSkill(usable_ids.pop()!, "Rigger", "The Hero is skilled in fixing minor damage to watercraft. If the boat or barge is stationary and has not moved during the last turn then if the Hero is in contact with it, he may repair one location previously damaged or set on fire. ie, a paddle or mast. The Hero may do nothing else that turn and the boat may not be moved. A boat cannot be repaired if an enemy model is in contact with the Hero or the watercraft. (MiM)", initialSkillGroups["Strength"]),
  QuickSkill(usable_ids.pop()!, "Handyman", "The warrior is skilled in fixing minor damage on a wagon, cart or coach. If the wagon is stationary and has not moved during the last turn then if the warrior is in contact with the wagon, he may repair one previously damaged wheel. The Hero may do nothing else that turn and the wagon may not be moved. He can even set in a new wheel if it flew off. A wagon cannot be repaired if an enemy model is in contact with the handyman or the wagon, as the situation is far too dangerous to focus on the cart. (BTB)", initialSkillGroups["Strength"]),
  QuickSkill(usable_ids.pop()!, "Mighty Blow", "The warrior knows how to use his strength to maximum effect. When attacking with any sort of Hammer or Mace or its two handed variant you gain +1 to Wound (MiM)", initialSkillGroups["Strength"]),
  QuickSkill(usable_ids.pop()!, "Heavy Hitter", "The warrior always stuns in place of knocking down with attacks from this weapon. Helmets still work and units that can't be stunned still can't. Any item with concussion rule.", initialSkillGroups["Strength"]),
  QuickSkill(usable_ids.pop()!, "Resilience", "The warrior has the fortitude to survive blows that would otherwise kill a lesser fighter. When this character suffers a wound they may reduce the injury roll by 1 by passing a toughness test. Note that a natural 6 will always take a model OOA regardless of any other modifiers.  If reduced to a zero then the warrior is not knocked down. Does not stack with the Jump Up skill.", initialSkillGroups["Strength"]),
  QuickSkill(usable_ids.pop()!, "Splintering Blow", "Each Axe strike from the warrior rends armour like the trunk of a tree. The armour modifier from all axes is increased to -2. (MiM)", initialSkillGroups["Strength"]),
  QuickSkill(usable_ids.pop()!, "Beat Down", "When attacking with any sort of Morning Star or Flail, if you HIT an enemy in the first round of combat, you may continue the strength bonus onto the next round of combat. The bonus will last as long as you keep hitting an opponent each round. (MiM)", initialSkillGroups["Strength"]),
  QuickSkill(usable_ids.pop()!, "Fortitude", "the warrior rerolls all side effects results of drugs, even when beneficial. (MiM)", initialSkillGroups["Strength"]),
  QuickSkill(usable_ids.pop()!, "Impressive Bulk", "whenever the hero makes a Strength or Toughness test he may add +1 to the  characteristic for the purposes of the test. (MiM)", initialSkillGroups["Strength"]),
]