name: CI

on: [pull_request] # we want the workflow to trigger on commits to PRs only

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install root dependencies
        run: yarn install

      - name: Lint app
        run: yarn lint
