name: CI

on: [pull_request] # we want the workflow to trigger on commits to PRs only

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Cache NPM # leverage npm cache on repeated workflow runs if package.json didn't change
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

  # security: # in this and following jobs, only the last step will be different
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout commit
  #       uses: actions/checkout@v2

  #     - name: Use Node.js
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: '12.x'

  #     - name: Cache NPM
  #       uses: actions/cache@v1
  #       with:
  #         path: ~/.npm
  #         key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
  #         restore-keys: |
  #           ${{ runner.os }}-node-

  #     - name: Install Dependencies
  #       run: npm ci

  #     - name: Run security check
  #       run: npm run audit-security

  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout commit
  #       uses: actions/checkout@v2

  #     - name: Use Node.js
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: '12.x'

  #     - name: Cache NPM
  #       uses: actions/cache@v1
  #       with:
  #         path: ~/.npm
  #         key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
  #         restore-keys: |
  #           ${{ runner.os }}-node-

  #     - name: Install Dependencies
  #       run: npm ci

  #     - name: Run tests
  #       run: npm run test
